user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  time:
    expired: 2
micropost:
  content:
    max_length: 140
  picture:
    size: 5
gravatar:
  size: 50
follow:
  gravatar:
    size: 30
